apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-rhdh-installer
  annotations:
    github.com/project-slug: HusneShabbir/ai-rhdh-installer
spec:
  type: other
  lifecycle: unknown
  owner: user:default/husneshabbir
